name: Check CSS Selectors on Jira Issue Transition
 
on:
  repository_dispatch:
    types:
      - check_css_changes
 
jobs:
  check_selectors:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Get PR Number
        id: get_pr_number
        run: |
          issueKey="${{ github.event.client_payload.issueKey }}"
          api_url="https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${issueKey}"
          PR_NUMBER=$(curl -s -X GET \
              -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${issueKey}" | jq -r 'if length > 0 then .[0].number else null end')

          if [ -n "$PR_NUMBER" ]; then
            echo "::set-output name=pr_number::$PR_NUMBER"
          else
            echo "Failed to retrieve PR number."
            exit 1
          fi
