name: Change Detection

on:
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-latest
    env:
      ENV_SECRET: ${{ secrets.JIRA_API_TOKEN_ENVIRONMENT }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List Branches and Set Outputs
        id: list-branches
        run: |
          git fetch --all --prune
          git branch -a
          branches=$(git branch -a)
          if echo "${branches}" | grep -q "${{ github.event.client_payload.issueKey }}"; then
            echo "${{ github.event.client_payload.issueKey }} branch exists."
            echo "TARGET_BRANCH=exists" >> $GITHUB_ENV
          else
            echo "Branch ${{ github.event.client_payload.issueKey }} does not exist. Skipping subsequent steps."
            echo "TARGET_BRANCH=not_exists" >> $GITHUB_ENV
            exit 0
          fi

      - name: List modified files
        id: list-files
        run: |
          git fetch origin
          # Check for changes in the /server/database folder
          git diff --name-only origin/main origin/${{ github.event.client_payload.issueKey }} -- 'server/database/*' > changed_database_files.txt
          if test -s changed_database_files.txt; then
            echo "CHANGED_DATABASE_FILES=1" >> $GITHUB_ENV
          else
            echo "CHANGED_DATABASE_FILES=0" >> $GITHUB_ENV
          fi
          # Check for changes in /server/models folder or ItemDefinition.ts
          git diff --name-only origin/main origin/${{ github.event.client_payload.issueKey }} -- 'server/models/*' 'src/threatmodel/ItemDefinition.ts' > changed_models_files.txt
          if test -s changed_models_files.txt; then
            echo "CHANGED_MODELS_FILES=1" >> $GITHUB_ENV
          else
            echo "CHANGED_MODELS_FILES=0" >> $GITHUB_ENV
          fi

      - name: Update JIRA Custom Fields
        if: (env.CHANGED_DATABASE_FILES == '1' || env.CHANGED_MODELS_FILES == '1') && env.TARGET_BRANCH == 'exists'
        run: |
          # Extract issueKey from the payload
          issueKey=${{ github.event.client_payload.issueKey }}
          # Your JIRA API URL
          jiraUrl="https://testjiragitautomation.atlassian.net/rest/api/3/issue/${issueKey}"
          # Your JIRA Custom Field IDs
          customFieldIdAPI="customfield_10040"
          customFieldIdSchema="customfield_10041"
          # JIRA username (email)
          jiraUsername="muhammadshoaibajk@gmail.com"
          # JIRA API token or password
          jiraToken=$ENV_SECRET

          # Update custom field for API change
          if [ "${{ env.CHANGED_DATABASE_FILES }}" == "1" ]; then
            curl -X PUT \
              -H "Content-Type: application/json" \
              -u "${jiraUsername}:${jiraToken}" \
              -d '{
                "fields": {
                  "customfield_10040": "TRUE"
                }
              }' \
              "${jiraUrl}"
          fi

          # Update custom field for schema change
          if [ "${{ env.CHANGED_MODELS_FILES }}" == "1" ]; then
            curl -X PUT \
              -H "Content-Type: application/json" \
              -u "${jiraUsername}:${jiraToken}" \
              -d '{
                "fields": {
                  "customfield_10041": "TRUE"
                }
              }' \
              "${jiraUrl}"
          fi
