name: Find Current Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  find-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR number
        run: echo "Your PR is ${{ github.event.number }}"
